#ifndef NEWPLAYERPLUGIN_GLOBAL_H
#define NEWPLAYERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEWPLAYERPLUGIN_LIBRARY)
#  define NEWPLAYERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEWPLAYERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEWPLAYERPLUGIN_GLOBAL_H
