#ifndef CHAMPIONSHIPINTERFACES_GLOBAL_H
#define CHAMPIONSHIPINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHAMPIONSHIPINTERFACES_LIBRARY)
#  define CHAMPIONSHIPINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHAMPIONSHIPINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHAMPIONSHIPINTERFACES_GLOBAL_H
